<?php

namespace Tests\Feature\Pembimbing;

use App\Mahasiswa;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class SubmitPembimbingTest extends TestCase
{
    use WithFaker, RefreshDatabase;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->mahasiswa = create(Mahasiswa::class);
    }

    /** @test */
    public function a_student_can_choose_thesis_supervisor()
    {
        $this->withoutExceptionHandling();

        $this->signInAsMahasiswa();

        $this->get(route('admin.pembimbing.create'))
            ->assertStatus(200);

    }
}
